<?php

namespace GT\TournoiBundle\Repository;

use Doctrine\ORM\EntityRepository;
//use TournoiBundle\Entity\Score;

/**
 * RencontreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RencontreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRencontresAvecScoreEtEquipe()
    {
//        $query = $this->getEntityManager()
//            ->createQuery(
//                "SELECT r, s FROM TournoiBundle:Rencontre r".
//                    "JOIN TournoiBundle:Score s"
//            );
//        
//        return $query->getResult();
    }    
}
