arbitres_index:
    path:     /
    defaults: { _controller: "TournoiBundle:Arbitre:index" }
    methods:  GET

arbitres_show:
    path:     /{id}/show
    defaults: { _controller: "TournoiBundle:Arbitre:show" }
    methods:  GET

arbitres_new:
    path:     /new
    defaults: { _controller: "TournoiBundle:Arbitre:new" }
    methods:  [GET, POST]

arbitres_edit:
    path:     /{id}/edit
    defaults: { _controller: "TournoiBundle:Arbitre:edit" }
    methods:  [GET, POST]

arbitres_delete:
    path:     /{id}/delete
    defaults: { _controller: "TournoiBundle:Arbitre:delete" }
    methods:  DELETE
